# Generated by Django 2.0.2 on 2018-06-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogging',
            name='body',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
