# Generated by Django 2.0.2 on 2018-06-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingtime', '0003_auto_20180628_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogging',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
