# Generated by Django 2.0.2 on 2018-07-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggingtime', '0004_blogging_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogging',
            name='body',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
